"""TaskList

Revision ID: ba82995a7ada
Revises: 1fac7ed67248
Create Date: 2025-10-04 03:02:25.914818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba82995a7ada'
down_revision: Union[str, Sequence[str], None] = '1fac7ed67248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklists', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklists', 'default')
    # ### end Alembic commands ###
